apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  containers:
    # Jenkins inbound agent (required)
    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: IfNotPresent
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: 'http://ITI-GP-Cluster-jenkins-alb-1026072163.eu-north-1.elb.amazonaws.com'
      resources:
        requests:
          cpu: '100m'
          memory: '256Mi'
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    # Additional tools
    - name: git
      image: alpine/git:latest
      command: ['sleep']
      args: ['99d']
      tty: true

    - name: kaniko
      image: 428346553093.dkr.ecr.eu-north-1.amazonaws.com/kaniko-aws:latest
      command: ['/busybox/sleep']
      args: ['99999']
      tty: true

  volumes:
    - name: workspace-volume
      emptyDir: {}
