apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
  namespace: jenkins
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - 9999999
  restartPolicy: Never
