apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  containers:
    - name: git
      image: alpine/git:latest
      command:
        - sleep
      args:
        - 99d
      tty: true

    - name: helm
      image: dtzar/helm-kubectl:latest
      command:
        - sleep
      args:
        - 99d
      tty: true

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/sleep
      args:
        - '99999'
      tty: true

    - name: tester
      image: ubuntu
      command:
        - sleep
      args:
        - 99d
      tty: true

    - name: mailer
      image: alpine:latest
      command:
        - sleep
      args:
        - 99d
      tty: true

    - name: argocd-syncer
      image: bstar999/argocd-syncer
      command:
        - sleep
      args:
        - 99d
      tty: true
