apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.19.0-debug
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - '9999999'
      env:
        - name: AWS_REGION
          value: 'eu-north-1'
        - name: AWS_DEFAULT_REGION
          value: 'eu-north-1'
        - name: AWS_SDK_LOAD_CONFIG
          value: 'true'
        # Enable Pod Identity credential provider
        - name: AWS_EC2_METADATA_DISABLED
          value: 'false'
        # Use Pod Identity through IMDS
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: '10'
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: '3'
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
